package com.decouikit.atom.menu.model

enum class NavigationItemType {
    HEADER,
    MENU_LIST,
    MENU_CARDS,
    MENU_PARALLAX,
    MENU_RTL_COLOR_CHANGE,
    MENU_LOGIN,
    MENU_REGISTER,
    MENU_FORGOT_PASSWORD,
    MENU_OLD_NEW_PASSWORD,
    MENU_IMAGE_GALLERY,
    MENU_SPLASH_SCREEN,
    MENU_CHECKBOX,
    MENU_SEARCH,
    MENU_SMALL_COMPONENTS,
    MENU_WIZARD,
    MENU_TAB,
    MENU_TIMELINE,
    MENU_RADIO,
    MENU_RANGE,
    MENU_TOGGLE,
    MENU_SELECT,

    LIST_EXPANDABLE,
    LIST_EXPANDABLE_1,

    LIST_DRAG_DROP,
    LIST_DRAG_DROP_1,

    LIST_SWIPE_TO_DISMISS,
    LIST_SWIPE_TO_DISMISS_1,
    LIST_SWIPE_TO_DISMISS_2,

    LIST_GOOGLE_CARDS_1,
    LIST_GOOGLE_CARDS_2,
    LIST_GOOGLE_CARDS_3,
    LIST_GOOGLE_CARDS_4,
    LIST_GOOGLE_CARDS_5,
    LIST_GOOGLE_CARDS_6,
    LIST_GOOGLE_CARDS_7,
    LIST_GOOGLE_CARDS_8,
    LIST_GOOGLE_CARDS_9,
    LIST_GOOGLE_CARDS_10,

    IMAGE_GALLERY_CATEGORIES,

    SPLASH_SCREEN_SIMPLE,

    PARALLAX_FRIENDS,
    PARALLAX_SHOPPING,
    PARALLAX_PROFILE,

    SEARCH_SIMPLE,
    SEARCH_TOP_BAR,

    TAB_BOTTOM_TEXT,
    TAB_BOTTOM_ICONS,
    TAB_TOP_TEXT,
    TAB_TOP_ICONS,

    WIZARD_WALK_THROUGH,
    WIZARD_E_COMMERCE,
    WIZARD_PROFILES,
    WIZARD_SOCIAL,

    LOGIN_LOGO_1,

    REGISTER_LOGO_1,

    FORGOT_PASSWORD_SIMPLE,

    OLD_NEW_PASS_WITH_BG,

    CHECKBOX_SIMPLE_LEFT,
    CHECKBOX_SIMPLE_RIGHT,
    CHECKBOX_AVATAR_LEFT,
    CHECKBOX_AVATAR_RIGHT,
    CHECKBOX_ICON_LEFT,
    CHECKBOX_ICON_RIGHT,

    RADIO_BUTTON_SIMPLE_LEFT,
    RADIO_BUTTON_SIMPLE_RIGHT,
    RADIO_BUTTON_AVATAR_LEFT,
    RADIO_BUTTON_AVATAR_RIGHT,
    RADIO_BUTTON_ICON_LEFT,
    RADIO_BUTTON_ICON_RIGHT,

    TOGGLE_SIMPLE,
    TOGGLE_DESC,
    TOGGLE_GROUP,

    SMALL_COMPONENTS_ALL,

    RTL_COLOR_CHANGE_TEST,

    SINGLE_SELECT,
    MULTI_SELECT,

    RANGE_ALL,

    TIMELINE_LEFT,
    TIMELINE_CENTER,
    TIMELINE_RIGHT
}